language: matlab
matlab:
  - R2020a
  - R2020b
script:
  - matlab -batch "addpath dev-kit; blah_launchtests"
  - make test
  - make dist
  - make toolbox
  - make clean
# Remove this if you don't use codecov.io
after_script: bash <(curl -s https://codecov.io/bash)
